### ISSUE TITLE
Adding comments to blog-example

### ISSUE THREAD

**Issue by davidbe** [drewolson/blox#1]
Hi,

Would you consider adding comments to the example? I'm struggling how to handle associations with ecto and forms...

david

**Comment by drewolson** [comment]
Hi @davidbe. I think a better approach would be for me to flesh out the README with more details. I'd like to stay away from commented the code as I don't generally comment but rather prefer to write small functions with clear names.

**Comment by davidbe** [comment]
Hi @drewolson - ah, a misunderstanding. With comments, I'd meant in the application, not in the code: there are posts and people can comment on the posts. Like I wrote, I'm struggling in handling associations in ecto and forms. The association between a post and commands would be "has-many". That would be a good expansion to this example-app and a way how to use associations in phoenix! :)

**Comment by drewolson** [comment]
Ah, yes, ok! I'll reopen this and add them.

**Comment by drewolson** [comment]
Closed with 89397cb476c44ad30c60568abc4b47134d430e99
